(define (f hoge hoge2)
  (display hoge)
  (display " ")
  (write hoge)
  (display " ")
  (write hoge2)
  (display " ")
  (display (eq? hoge hoge2))
  (display " ")
  (print hoge)
  )

(print '("(" ")"))

(f ':hoge ':hoge)
(f 'hoge: 'hoge:)
(f 'hoge: ':hoge)
(f '|:hoge| '|:hoge|)
(f '|hoge:| '|hoge:|)
(f '|:hoge| '|hoge:|)
(f '#:hoge '#:hoge)
(f '#:hoge ':hoge)
(f '#:hoge 'hoge:)
