(import (chicken io))
(require-extension chicken.io)

;; (import wrapper)
;; (load "chicken/wrapper.so")
;; (test 'a '(b c))
;; (define read-line-x read-line)
(eval '(define (f)(read-line)))
(define hoge read-line)
(print (eval '(f)))
;; (print (eval '(read-line-x)(interaction-environment)))
