(include "util.sch")

(defineCPS main ^()
  -1 ^(x)
  if(x < 0)(print("0より小さい\n"))
  (print("0以上\n"))^()
  if(x > 0)(print("0より大きい\n"))
  (print("0以下\n"))^()
  if(x = 0)(print("0と等しい\n")) nop ^()
  if(x <> 0)(print("0と異なる\n")) nop ^()
  unless(x <= 0)(print("0以下ではない\n")) ^()
  unless(x >= 0)(print("0以上ではない\n")) ^()
  exit 0)
