(include "util.sch")

(defineCPS main ^()
  -1 ^(x)
  if(x < 0)(print("0未満\n")) nop ^()
  if(x > 0)(print("0より大きい\n")) nop ^()
  if(x = 0)(print("0と等しい\n")) nop ^()
  if(x <> 0)(print("0と異なる\n")) nop ^()
  if(x <= 0)(print("0以下\n")) nop ^()
  if(x >= 0)(print("0以上\n")) nop ^()
  if(x < 0)(0 - x) x ^(absx)
  print("|" x "|=" absx "\n")^()
  if(x < 0)(x * -1) x ^(x)
  print("|x|=" x "\n")^()
  exit 0)
